# Generated by Django 5.1 on 2024-08-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_teacherprofile_is_teacher_user_is_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='teach_dob',
        ),
    ]
