# Generated by Django 5.1.1 on 2024-10-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0006_alter_teacherprofile_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='subject',
            field=models.CharField(choices=[('MATHS', 'Mathematics'), ('PHY', 'Physics'), ('CHEM', 'Chemistry'), ('BIO', 'Biology'), ('ENG', 'English'), ('GEO', 'Geography'), ('HIS', 'History'), ('ECO', 'Economics'), ('COMPSCI', 'Computer Science')], default='SELECT', max_length=7),
        ),
    ]
